// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwissSystem.WebApp.DAL;

#nullable disable

namespace SwissSystem.WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208144422_Finals")]
    partial class Finals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwissSystem.WebApp.Models.FinalsBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FinalsPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("FinalsPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("SemifinalsAPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("SemifinalsAPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("SemifinalsBPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("SemifinalsBPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinalsPlayer1Id");

                    b.HasIndex("FinalsPlayer2Id");

                    b.HasIndex("SemifinalsAPlayer1Id");

                    b.HasIndex("SemifinalsAPlayer2Id");

                    b.HasIndex("SemifinalsBPlayer1Id");

                    b.HasIndex("SemifinalsBPlayer2Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.HasIndex("WinnerId");

                    b.ToTable("FinalsBrackets");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Player1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Id")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.FinalsBracket", b =>
                {
                    b.HasOne("SwissSystem.WebApp.Models.Player", "FinalsPlayer1")
                        .WithMany()
                        .HasForeignKey("FinalsPlayer1Id");

                    b.HasOne("SwissSystem.WebApp.Models.Player", "FinalsPlayer2")
                        .WithMany()
                        .HasForeignKey("FinalsPlayer2Id");

                    b.HasOne("SwissSystem.WebApp.Models.Player", "SemifinalsAPlayer1")
                        .WithMany()
                        .HasForeignKey("SemifinalsAPlayer1Id");

                    b.HasOne("SwissSystem.WebApp.Models.Player", "SemifinalsAPlayer2")
                        .WithMany()
                        .HasForeignKey("SemifinalsAPlayer2Id");

                    b.HasOne("SwissSystem.WebApp.Models.Player", "SemifinalsBPlayer1")
                        .WithMany()
                        .HasForeignKey("SemifinalsBPlayer1Id");

                    b.HasOne("SwissSystem.WebApp.Models.Player", "SemifinalsBPlayer2")
                        .WithMany()
                        .HasForeignKey("SemifinalsBPlayer2Id");

                    b.HasOne("SwissSystem.WebApp.Models.Tournament", "Tournament")
                        .WithOne("FinalsBracket")
                        .HasForeignKey("SwissSystem.WebApp.Models.FinalsBracket", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwissSystem.WebApp.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("FinalsPlayer1");

                    b.Navigation("FinalsPlayer2");

                    b.Navigation("SemifinalsAPlayer1");

                    b.Navigation("SemifinalsAPlayer2");

                    b.Navigation("SemifinalsBPlayer1");

                    b.Navigation("SemifinalsBPlayer2");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Match", b =>
                {
                    b.HasOne("SwissSystem.WebApp.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwissSystem.WebApp.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwissSystem.WebApp.Models.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwissSystem.WebApp.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Round");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Player", b =>
                {
                    b.HasOne("SwissSystem.WebApp.Models.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Round", b =>
                {
                    b.HasOne("SwissSystem.WebApp.Models.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SwissSystem.WebApp.Models.Tournament", b =>
                {
                    b.Navigation("FinalsBracket");

                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
